# ===== Kotlin / KMP 配置 =====
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true

# ===== Android 配置 =====
android.useAndroidX=true
android.nonTransitiveRClass=true

# ===== Gradle 性能优化 =====
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# ===== Compose Multiplatform =====
org.jetbrains.compose.experimental.uikit.enabled=true
